### ISSUE TITLE
Feature request: Replace login with Coinbase Wallet SDK

### ISSUE THREAD

**Issue by saulmc** [xmtp-labs/xmtp-inbox-mobile#69]
### Is your feature request related to a problem?

The app does not currently have an EOA connection flow that works consistently.

(This does not address the discussion of Privy embedded wallet vs Coinbase smart wallet, to be documented elsewhere).

### Describe the solution to the problem

Use the simplest option for smooth EOA connection.

### Describe the uses cases for the feature

This gets us a smooth login flow for Coinbase Wallet users, which should include everyone at Ephemera.

### Additional details

https://github.com/MobileWalletProtocol/wallet-mobile-sdk?tab=readme-ov-file

**Comment by alexrisch** [comment]
Added in https://github.com/xmtp-labs/xmtp-inbox-mobile/pull/104
