### ISSUE TITLE
Wallet connect errors with no third web file

### ISSUE THREAD

**Issue by nplasterer** [xmtp-labs/xmtp-inbox-mobile#72]

**Comment by alexrisch** [comment]
Do you have an error/screenshot?

**Comment by nplasterer** [comment]
Ahh ya sorry

![image](https://github.com/xmtp-labs/xmtp-inbox-mobile/assets/3522670/73574e13-0dfb-44d9-9be0-ef72383a92c4)

**Comment by alexrisch** [comment]
Should be fixed in Testflight build #34
