### ISSUE TITLE
Bug: Add member to existing group modal displays unrecognized/invalid addresses

### ISSUE THREAD

**Issue by saulmc** [xmtp-labs/xmtp-inbox-mobile#89]
### Describe the bug

The modal for entering the address of a new group chat member contains a list of addresses that I have not interacted with and do not have the "0x" prefix required to be a valid address.

<img src ="https://github.com/xmtp-labs/xmtp-inbox-mobile/assets/510695/2ed3787d-3619-4b58-b9f1-53f72fac1881" width=250/>

### Expected behavior

For the current scope, this modal is expected to have no preloaded addresses.

In the future, we'll intelligently recommend addresses to add to the group.

### Steps to reproduce the bug

- Create a group
- Tap the button to add members

**Comment by alexrisch** [comment]
Fixed in Testflight 35
Will close out this issue, but feel free to reopen if it's still a problem
