### ISSUE TITLE
Bug: Cannot add new member to existing group chat

### ISSUE THREAD

**Issue by saulmc** [xmtp-labs/xmtp-inbox-mobile#90]
### Describe the bug

This error is displayed when adding a member to an existing group chat:

<img src="https://github.com/xmtp-labs/xmtp-inbox-mobile/assets/510695/623e2c3c-ee2b-4f27-a5a8-98edf2fb8499" width = 250/>

### Expected behavior

The new member is added to the chat.

### Steps to reproduce the bug

- Start a group
- Tap the button to add members
- Paste in another test address
- Tap add

**Comment by alexrisch** [comment]
This one took a bit, it requires bumping lib XMTP, also included in the push notifications PR

What this means is old addresses made with the current TestFlight will not work, which is a pain, but should be a one time/alpha pain

**Comment by alexrisch** [comment]
This is fixed in the latest TF
However to reiterate, only accounts made on this testflight and future ones will work
